### PR TITLE
Fix #201: Fix issue with oppiabot tagging @undefined to add a label

### LINKED ISSUE #201: Bot is asking @undefined user to add changelog label to the PR
OppiaBot is leaving is asking undefined users for adding a changelog label.

`Hi @undefined, @undefined -- could one of you please add the appropriate changelog label to this pull request? Thanks!`

Comment link: https://github.com/oppia/oppia/pull/11957#issuecomment-779131071

### PR DESCRIPTION
**Pull request by jameesjohn**
## Explanation
Fixes #201 by waiting for 5 seconds in order to allow GitHub to request reviews from the code owners.

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

**Review by vojtechjelinek — APPROVED** [review]
LGTM!

**Comment by vojtechjelinek** [comment]
@jameesjohn Please release this

**Comment by SAEb-ai** [comment]
@jameesjohn @vojtechjelinek  I think that this issue is still not fixed.
See:(https://github.com/oppia/oppia/pull/12361#issuecomment-809435039)

**Comment by vojtechjelinek** [comment]
@SAEb-ai Thanks! I reopened the original issue.

**Pull request merged**
