### PR TITLE
Add logic to bypass project owner if they are PR author

### PR DESCRIPTION
**Pull request by kevinlee12**
## Explanation
Bypass the project owner if they are the PR author. 

## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

**Comment by seanlip** [comment]
Hi @kevinlee12, just checking, did you complete the checklist?

**Comment by kevinlee12** [comment]
As for the checklist, I only got the first one to work, I was stuck getting the necessary keys for these fields for the environment variables:
```

# Details of the Gmail account. This is required to access the Spreadsheet.
CLIENT_SECRET=None
CREDENTIALS=None

# Details of the Spreadsheet used for CLA checking.
SHEETS_API_CREDENTIALS=None
SPREADSHEET_ID=None
```

**Comment by kevinlee12** [comment]
@apb7

**Comment by seanlip** [comment]
Hi @kevinlee12, did you manage to test this (with Apurv's notes?) Please confirm so that we can review + merge it. Thanks!

**Comment by kevinlee12** [comment]
Unfortunately, I have been fairly bogged down by other things to test this. It's on my queue.

**Comment by kevinlee12** [comment]
Just leaving a comment here that @apb7

**Comment by kevinlee12** [comment]
@seanlip, I've been able to test this and it looks good on the test repo!

**Pull request merged**
