### PR TITLE
Add setup for circleci

### PR DESCRIPTION
**Pull request by ankita240796**
## Explanation
- Adds setup config for circleci tests

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

These tests aren't required since the PR does not affect any of the oppiabot features.

### CODE REVIEW

**Comment by seanlip** [comment]
Let's get this in first, then CircleCI can use it. I'm working on the repo addition now.

**Comment by seanlip** [comment]
I think this is now done, please could you check and confirm? Dashboard is [here](https://app.circleci.com/pipelines/github/oppia/oppiabot).

**Comment by seanlip** [comment]
(Let me know if you need me to do anything further, like hook up specific checks to PRs -- just send me the instructions and I'll follow them. Thanks!)

**Comment by ankita240796** [comment]
Thanks @seanlip!

**Pull request merged**
