### PR TITLE
Fixed #198: Remove LGTM label if changes are requested.

### LINKED ISSUE #198: Remove LGTM label if changes are requested.
If after the LGTM label is placed, a reviewer request for changes then the LGTM label must be removed.
Ref: [Link](https://github.com/oppia/oppia/pull/11701#pullrequestreview-579995313)

### PR DESCRIPTION
**Pull request by b2pacific**
## Explanation
Fixed #198: Remove LGTM label if changes are requested.

## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

**Review by jameesjohn — CHANGES_REQUESTED** [review]
Thanks, @b2pacific!
Can you provide a link to a PR where this was tested? Also, can you write tests for the newly added feature?

**Comment by b2pacific** [comment]
Yes, I can write the tests. Once this pr is merged can I make another pr for the tests? But the tests for this pr is still failing.

**Comment by jameesjohn** [comment]
I meant a link to where the feature was tested manually.
Also, the tests need to be written in this PR. The frontend tests are failing due to code coverage being less than 100%

**Comment by jameesjohn** [comment]
You can run the tests locally via `npm test`

**Comment by jameesjohn** [comment]
Hi, @b2pacific any updates on this?

**Comment by Naman-1234** [comment]
@vojtechjelinek  and @jameesohn  Sir I think the author is not able to tackle this problem as there are more than 21 days. Could I take this issue and try to solve it. Please let me know.Thanks.

**Comment by vojtechjelinek** [comment]
@Naman-1234 Can you please comment on the issue itself, I will assign you then.

**Comment by Naman-1234** [comment]
Sure Sir

**Pull request closed without merging**
