### PR TITLE
Add custom stale package

### PR DESCRIPTION
**Pull request by apb7**
This PR adds the custom stale package (https://github.com/apb7/stale) which has been modified for Oppia's usage.
@kevinlee12, ptal! Thanks.

### CODE REVIEW

**Comment by seanlip** [comment]
Thanks @apb7!

Shouldn't "stale" be a repo on oppia, though? I can make one for you if you like -- how about oppiabot-stale?

**Comment by seanlip** [comment]
Also I suggest that the first commit to oppiabot-stale be a vanilla version of the "stale" library. The next commit should then be the changes you've made. This will allow us to track changes from the original lib.

**Comment by apb7** [comment]
Hi Sean, can we fork https://github.com/probot/stale for oppia? I can then send in a PR to make necessary changes.

**Comment by seanlip** [comment]
Done! Go for it :)

**Comment by apb7** [comment]
Oh, it is even possible to create "a fork of a fork": https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github?
I think I may have to delete the original fork I have on my account...

**Comment by kevinlee12** [comment]
@apb7, it looks like you've already created a PR for that, can I close this?

**Comment by apb7** [comment]
Sorry, I am bit confused Kevin. We have three PRs here -- this one in oppiabot for adding the custom package, [this ](https://github.com/oppia/oppiabot-stale/pull/1) one in oppiabot-stale, which is actually our custom package and [this](https://github.com/oppia/oppia/pull/5214) one in oppia, which changes the config file. We need all of these to go in.

**Comment by kevinlee12** [comment]
Never mind, I misunderstood what was going on.

**Comment by kevinlee12** [comment]
What you did here is okay.

**Comment by apb7** [comment]
Thank you, @kevinlee12 and @seanlip :)

**Pull request merged**
