### PR TITLE
Revert conditionals

### PR DESCRIPTION
**Pull request by apb7**
This PR reverts the conditionals changed in [PR #6 comment](https://github.com/oppia/oppiabot/pull/6#pullrequestreview-131447353). In general, the changes done in PR #6 are not equivalent to the required conditionals.

### CODE REVIEW

**Comment by seanlip** [comment]
@apb7, I have one question. How do you test these changes before they go live?

We really need to avoid false positives, otherwise developers will start ignoring the bot. What is the testing plan (both automated and manual) for ensuring that changes do not break the bot's functionality? Do we have one?

**Comment by apb7** [comment]
@seanlip: I have already set up another GitHub app on a separate Heroku account. This is installed on a test repository. Before making a PR, I test all the changes manually by making a number of different PRs to check-in all kinds of payloads.

**Comment by seanlip** [comment]
That sounds good, thanks @apb7. But in that case, how did this scenario make it past testing?

I would also suggest creating and maintaining a matrix of test scenarios for oppiabot, similar to what we currently do for the main Oppia release process. What do you think?

**Comment by apb7** [comment]
That is a great idea. We could develop a playground something like [this](https://github.com/probot/test).

**Pull request merged**
