### PR TITLE
Check PR Title for WIP

### PR DESCRIPTION
**Pull request by amey-kudari**
## Explanation
Check PR Title for WIP when PR is opened/closed/edited.

## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

**Comment by amey-kudari** [comment]
Hi! 
@kevinlee12 @ankita240796 please take a look
Thanks!

**Comment by kevinlee12** [comment]
@amey-kudari we’re actually moving this over to Github actions, please talk with @ankita240796 on the design.

**Comment by amey-kudari** [comment]
Hi! @kevinlee12 @ankita240796 
Github actions will only have read only [permission](https://developer.github.com/v3/apps/permissions/#permission-on-actions) on this event, so it can't comment on the PR. Can this PR please be reopened now.

**Comment by kevinlee12** [comment]
Please coordinate with Ankita on this, we don’t want to add anymore checks to this version of Oppiabot.

**Pull request closed without merging**
